---
title: "index"
author: Caroline
output: html_document
github_repo: https://carolineahler.github.io/trial_webpage/
---

hej med dig bob 
``` {css, echo=FALSE}
body {
background-color: navy;
color: white;
}


```
[Next Question](question2.html)

<br>

<button id="button1">Click me!</button>
<p id="message"></p>

<script>
document.getElementById("button1").addEventListener("click", function() {
  document.getElementById("message").innerHTML = "Button 1 was clicked!";
});
</script>

<br> 

<select id="dropdown">
  <option value="option1">Dit første valg</option>
  <option value="option2">Option 2</option>
  <option value="option3">Option 3</option>
</select>

<p id="message"></p>

<script>
document.getElementById("dropdown").addEventListener("change", function() {
  var selectedOption = document.getElementById("dropdown").value;
  document.getElementById("message").innerHTML = "Selected option: " + selectedOption;
});
</script>


## Write a Python code to calculate the sum of 5 and 7.

<textarea id="user-code"></textarea>
<button id="run-code">Run Code</button>
<div id="output"></div>

<script>
document.getElementById("run-code").addEventListener("click", function() {
  var userCode = document.getElementById("user-code").value;
  try {
    var result = eval(userCode);
    if (result === 12) {
      document.getElementById("output").innerHTML = "Correct!";
      document.body.style.backgroundColor = "green";
    } else {
      document.getElementById("output").innerHTML = "Try again.";
      document.body.style.backgroundColor = "red";
    }
  } catch (error) {
    document.getElementById("output").innerHTML = "Error!";
    document.body.style.backgroundColor = "red";
  }
});
</script>

<style>
#user-code {
  width: 100%;
  height: 100px;
}
#run-code {
  margin-top: 10px;
}
#output {
  margin-top: 10px;
  font-weight: bold;
}
</style>